timeout: 0
quiet: yes
graphics: yes

default_entry: 1

/Arch Linux (linux)
    protocol: linux
    path: boot():/vmlinuz-linux
    cmdline: root=PARTUUID=202add72-e552-4cb4-b721-86c98d132ad7 zswap.enabled=0 rootflags=subvol=@ rw rootfstype=btrfs resume=UUID=6f07a5f8-1dcc-4ef8-bd3f-3f2e16ced860 resume_offset=5074338 quiet loglevel=3 rd.systemd.show_status=false rd.udev.log_level=3 systemd.show_status=false vt.global_cursor_default=0 splash
    module_path: boot():/initramfs-linux.img
