monitor.bluez.rules = [
  {
    matches = [
      {
        node.name = "~bluez_output.*"
      }
    ]
    actions = {
      update-properties = {
        session.suspend-on-idle = true
        # Time in seconds before closing the idle stream channel
        session.suspend-on-idle-timeout = 2
      }
    }
  }
]

