# Application bindings

bindd = ALT, RETURN, Terminal, exec, uwsm-app -- $terminal

bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- $fileManager --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- $fileManager --new-window "$(omarchy-cmd-terminal-cwd)"

bindd = SUPER SHIFT, B, Browser, exec, uwsm-app -- $browser

bindd = SUPER SHIFT ALT, B, Browser (private), exec, uwsm-app -- $browser --private-window

bindd = SUPER SHIFT, N, Editor, exec, $terminal -e nvim

bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker

bindd = SUPER SHIFT, O, Obsidian, exec, uwsm-app -- obsidian -disable-gpu --enable-wayland-ime

bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime

bindd = SUPER SHIFT, S, SLack, exec, uwsm-app -- slack

bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- bitwarden

bindd = SUPER, W, Tema, exec, uwsm-app -- tema


# Web App bindings

# If your web app url contains '#', type it as '##' to prevent hyprland treating it as a comment

bindd = SUPER SHIFT, M, Youtube Music, exec, chromium --app=https://music.youtube.com/

bindd = SUPER SHIFT, G, Google Messages, exec, chromium --app=https://messages.google.com/web/conversations


# Close applications

bindd = ALT, W, Close window, killactive,

