# Application bindings

bindd = ALT, RETURN, Terminal, exec, uwsm-app -- $terminal

bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- $fileManager --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- $fileManager --new-window "$(omarchy-cmd-terminal-cwd)"

bindd = SUPER SHIFT, B, Browser, exec, uwsm-app -- $browser

bindd = SUPER SHIFT ALT, B, Browser (private), exec, uwsm-app -- $browser --private-window

bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor

bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker

bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"

bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime

bindd = SUPER SHIFT, S, SLack, exec, uwsm-app -- slack

bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- bitwarden

bindd = SUPER, W, Tema, exec, uwsm-app -- tema


# Web App bindings

# If your web app url contains '#', type it as '##' to prevent hyprland treating it as a comment

bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"

bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus-webapp "Youtube Music" "https://music.youtube.com/"

bindd = SUPER SHIFT, G, Google Messages, exec, omarchy-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"

bindd = SUPER SHIFT, P, Google Photos, exec, omarchy-launch-or-focus-webapp "Google Photos" "https://photos.google.com/"


# Close applications

bindd = ALT, W, Close window, killactive,

bindd = CTRL ALT, DELETE, Close all windows, exec, omarchy-hyprland-window-close-all

