# Copy / Paste

bind = SUPER, C, sendshortcut, CTRL, Insert, activewindow

bind = SUPER, V, sendshortcut, SHIFT, Insert, activewindow

bind = SUPER, X, sendshortcut, CTRL, X, activewindow

bind = SUPER CTRL, V, exec, walker -m clipboard

