# Default wayland media controls

# bindl =, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
# bindle =, XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_SINK@ 5%+
# bindle =, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_SINK@ 5%-
# bindle = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-
# bindle = ,XF86MonBrightnessUp, exec, brightnessctl s 10%+
# bindl =, XF86AudioPlay, exec, playerctl play-pause # Toggles play/pause
# bindl =, XF86AudioNext, exec, playerctl next 
# bindl =, XF86AudioPrev, exec, playerctl previous
#
# # Precise 1% multimedia adjustments with Alt modifier
#
# bindled = ALT, XF86AudioRaiseVolume, Volume up precise, exec, wpctl set-volume @DEFAULT_SINK@ 1%+
# bindled = ALT, XF86AudioLowerVolume, Volume down precise, exec, wpctl set-volume @DEFAULT_SINK@ 1%-
# bindled = ALT, XF86MonBrightnessUp, Brightness up precise, exec, brightnessctl s 5%+
# bindled = ALT, XF86MonBrightnessDown, Brightness down precise, exec, brightnessctl s 5%-
#


# SwayOSD media controls

# Only display the OSD on the currently focused monitor
$swayosd-client = swayosd-client --monitor "$(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name')"

# Toggle mute (speakers)
bindl = , XF86AudioMute, exec, $swayosd-client --output-volume mute-toggle

# Toggle mute (mic)
bindl = , XF86AudioMicMute, exec, $swayosd-client --input-volume mute-toggle

# Volume raise with custom value
bindle = , XF86AudioRaiseVolume, exec, $swayosd-client --output-volume 5
# Volume lower with custom value
bindle = , XF86AudioLowerVolume, exec, $swayosd-client --output-volume -5

# # Capslock (If you don't want to use the backend)
# bind = , --release Caps_Lock, exec, swayosd-client --caps-lock
# # Capslock but specific LED name (/sys/class/leds/)
# bind = , --release Caps_Lock, exec, swayosd-client --caps-lock-led input19::capslock

# Cycle keyboard backlight
bindle = , XF86MonBrightnessUp, exec, $swayosd-client --brightness raise --device intel_backlight

# Brightness raise with custom value('+' sign needed)
bindle = , XF86MonBrightnessUp , exec, $swayosd-client --brightness +5

# Brightness lower with custom value('-' sign needed)
bindle = , XF86MonBrightnessDown, exec, $swayosd-client --brightness -10

# Play/Pause current player
bind = , XF86AudioPlay, exec, $swayosd-client --playerctl play-pause

# Next song for current player
bind = , XF86AudioNext, exec, $swayosd-client --playerctl next
