# Menus

bindd = SUPER, SUPER_L, Launch apps, exec, walker

bindd = SUPER, PERIOD, Emoji picker, exec, walker -m symbols

bindd = SUPER, SPACE, Actions menu, exec, walker menu

bindd = SUPER, ESCAPE, System menu, exec, walker-menu system

bindld = , XF86PowerOff, Power menu, exec, walker-menu system

bindd = SUPER, K, Show key bindings, exec, walker keybindings

bindd = , XF86Calculator, Calculator, exec, gnome-calculator


# Aesthetics

bindd = SUPER SHIFT, SPACE, Toggle top bar, exec, toggle-waybar

bindd = SUPER CTRL, SPACE, Set random background and generate theme colors, exec, ~/.local/bin/set-random-wallpaper

bindd = SUPER SHIFT CTRL, SPACE, Theme menu, exec, menu theme

bindd = SUPER, BACKSPACE, Toggle window transparency, exec, hyprctl dispatch setprop "address:$(hyprctl activewindow -j | jq -r '.address')" opaque toggle


# Notifications

bindd = SUPER CTRL, N, Open notification center, exec, swaync-client -t -sw

bindd = SUPER, COMMA, Trigger most recent notification, exec, swaync-client -a -sw

bindd = SUPER ALT, COMMA, Dismiss most recent notification, exec, swaync-client --close-latest -sw

bindd = SUPER CTRL, COMMA, Dismiss all notifications, exec, swaync-client --close-all -sw

bindd = SUPER SHIFT, COMMA, Toggle do-not-disturb mode, exec, swaync-client -d -sw


# Captures

bindd = SUPER CTRL, S, Screenshot with editing, exec, hyprshot -z -m region --raw --silent | satty --filename -

bindd = SUPER, S, Screenshot to clipboard without editing, exec, hyprshot -z -m region --clipboard-only --silent && notify-send "Screenshot Captured" "Saved to clipboard" --hint=int:transient:1

bind = SUPER, R, exec, screen-record

bindd = SUPER SHIFT, C, Color picker, exec, pkill hyprpicker || hyprpicker -a


# File sharing

bindd = SUPER CTRL SHIFT, S, Share, exec, omarchy-menu share


# Waybar-less information

bindd = SUPER CTRL ALT, T, Show time, exec, notify-send "    $(date +"%A %H:%M  —  %d %B W%V %Y")"


# Control panels

bindd = SUPER CTRL, A, Audio controls, exec, pulse

bindd = SUPER CTRL, B, Bluetooth controls, exec, $terminal --class=floating.Bluetui -e bluetui

bindd = SUPER CTRL, W, Wifi controls, exec, $terminal --class=floating.Gazelle -e gazelle

bindd = SUPER CTRL, T, Activity monitor, exec, $terminal --class=floating.Btop -e btop


# Package Management

bindd = SUPER CTRL, I, Install packages, exec, $terminal --class=floating.Pacman -e pi

bindd = SUPER CTRL, R, Remove Installed packages, exec, $terminal --class=floating.Pacman -e pr

bindd = SUPER CTRL, U, Full system update, exec, $terminal --class=floating.Pacman -e piu


# Dictation

bindd  = SUPER CTRL, X, Start dictation, exec, voxtype record start

binddr = SUPER CTRL, X, Stop dictation, exec, voxtype record stop


# Lock system

bindd = SUPER, L, Lock system, exec, hyprlock

# For laptops
# bindld=,switch:on:Lid Switch, Lcok and suspend system when lid is closed, exec, loginctl lock-session && systemctl suspend-then-hibernate

