github.com:
    users:
        bdgcypher:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: bdgcypher
