name = "system/power"
name_pretty = "System → Power"
icon = "󰐥"

[[entries]]
text = "Lock"
icon = "󰌾 "
actions = { "default" = "hyprlock" }
weight = 100

[[entries]]
text = "Reboot"
icon = "󰜉 "
actions = { "default" = "systemctl reboot" }
weight = 90

[[entries]]
text = "Screensaver"
icon = "󰿁 "
actions = { "default" = "screensaver toggle" }
weight = 85

[[entries]]
text = "Shutdown"
icon = "󰐥 "
actions = { "default" = "systemctl poweroff" }
weight = 80

[[entries]]
text = "Suspend"
icon = "󰒲 "
actions = { "default" = "systemctl suspend-then-hibernate" }
weight = 70
