name = "utilities"
name_pretty = "Utilities"
icon = ""

[[entries]]
text = "Clipboard History"
icon = "󱛢 "
actions = { "default" = "walker -m clipboard" }
weight = 100

[[entries]]
text = "Calculator"
icon = " "
actions = { "default" = "walker -m calc" }
weight = 90

[[entries]]
text = "Calendar"
icon = "󰃰 "
actions = { "default" = "ghostty --class=floating.Calendar -e aion" }
weight = 85

[[entries]]
text = "Capture"
icon = "󰄀 "
actions = { "default" = "walker -m menus:utilities/capture --width 250" }
weight = 80

[[entries]]
text = "Color Picker"
icon = " "
actions = { "default" = "pkill hyprpicker || hyprpicker -a -f hex && swayosd-client --custom-message \"Color copied to clipboard\" --custom-icon \"edit-copy\"" }
weight = 70

[[entries]]
text = "Emoji Picker"
icon = " "
actions = { "default" = "walker -m symbols --width 400" }
weight = 60

[[entries]]
text = "Volume Boost"
icon = "󰕾 "
actions = { "default" = "ghostty --class=floating.VolumeBoost -e volume-boost-toggle" }
weight = 50
