# Immediate boot autostarts


# Restore the last set wallpaper and theme
exec-once = awww-daemon
exec-once = awww img ~/.config/theme/current_wallpaper
exec-once = wal -R

# Initialize hyprsunset and hyprlock immediately after boot
exec-once = uwsm-app -- hyprsunset
exec-once = hyprlock



# Slow app launch fix -- set systemd vars (must run before uwsm-app calls)
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd --all
exec-once = gnome-keyring-daemon --start --components=secrets



# All other autostarts


exec-once = systemctl --user start elephant.service
exec-once = walker --gapplication-service
exec-once = uwsm-app -- hypridle
# exec-once = uwsm-app -- fcitx5 --disable notificationitem
exec-once = uwsm-app -- sunshine
exec-once = uwsm-app -- swaync
exec-once = uwsm-app -- swayosd-server
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Set GTK theme
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Materia-dark-compact'
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

# Mouseless
exec-once = flatpak run net.sonuscape.mouseless

# KDE Connect
exec-once = /usr/lib/kdeconnectd
exec-once = /usr/bin/kdeconnect-indicator
