general {
    lock_cmd = pidof hyprlock || hyprlock                    # lock screen
    before_sleep_cmd = loginctl lock-session                 # lock before suspend.
    after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on    # delay for PAM readiness, then turn on display.
    inhibit_sleep = 3                                        # wait until screen is locked
}

# listener {
#     timeout = 270                                                   # 4.5min
#     on-timeout = pidof hyprlock || (screensaver_script_placeholder) # start screensaver (if we haven't locked already)
# }

# Lock screen
listener {
    timeout = 300                                            # 5min
    on-timeout = loginctl lock-session                       # lock screen when timeout has passed
}

# Turn off keyboard backlight
listener {
    timeout = 300                                            # 5min
    on-timeout = brightnessctl -sd '*::kbd_backlight'  # save state and turn off keyboard backlight
    on-resume = brightnessctl -rd '*::kbd_backlight'         # restore keyboard backlight
}

# Turn off screen
listener {
    timeout = 300                                            # 5min
    on-timeout = hyprctl dispatch dpms off                   # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on && brightnessctl -r # screen on when activity is detected
}

# Conditional suspend (Only if on battery power)
listener {
    timeout = 330 # 5.5 minutes
    on-timeout = grep -q "Discharging" /sys/class/power_supply/BAT0/status && systemctl suspend-then-hibernate # suspend system if on battery power - hibernate after delay
}
