# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale


# Keep GTK apps from double-scaling
env = GDK_SCALE,0.9

# Laptop Internal Display (1080p)
monitor = eDP-1, 1920x1080@60, auto, 1.1

# Catch-all fallback for any other resolution (1440p, 4k, ultrawides, etc.)
monitor = , preferred, auto, 1.0

# Allow fractional scale factors without throwing warnings
debug:disable_scale_checks = true
