
# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale


# Keep GTK apps from double-scaling
env = GDK_SCALE,0.9

# Default setup for low-resolution displays like 1080p or 1440p
monitor = , preferred , auto, 1.1
debug:disable_scale_checks = true

# 4K Monitors
# monitor = , preferred, auto, 1
# debug:disable_scale_checks = true
