#!/bin/bash

# restart_launcher.sh - Make the launcher's cached menu tree match the menu TOMLs
# on disk, and make the running session -- compositor and shell -- match the
# config on disk.
#
# The menus are authored in quickshell/.config/quickshell/hayami-shell/menus/*.toml,
# but the launcher reads a snapshot of them generated by menus-json.py (for menus)
# and providers-json.py (for the Scripts provider). A menu edited on disk does not
# appear until that snapshot is re-baked, which is what `hayami-menu --refresh`
# does. Nothing has to be restarted for that content to show: the shell watches
# both cache files, so writing them is enough.
#
# The QML is the other half, and it *is* restarted. The shell live-reloads a file
# it already has open, but a restow is not an edit: stow replaces symlinks, and
# files the shell has never loaded -- a package that gained a module, a new state
# object, a menu -- arrive without anything the running instance was watching
# changing. A machine that was already running the shell therefore finished an
# install with the new QML on disk and the old QML in memory, which is why the
# bar only changed after a manual reload. So: reload when it is up, start when it
# is not (a first install, or the end of a migration).
#
# Hyprland is re-read from here as well, for the reason in the note above the
# reload below.

set -e

DOTFILES_DIR="$(dirname "$(dirname "$(realpath "$0")")")"
[ -d "$DOTFILES_DIR/hypr" ] || DOTFILES_DIR="$HOME/.dotfiles"

# The commands are looked up in the repo first, because this runs before (or
# instead of) a restow in some paths, and ~/.local/bin may not have them yet.
from_repo() {
	if [ -x "$DOTFILES_DIR/bin/.local/bin/$1" ]; then
		printf '%s\n' "$DOTFILES_DIR/bin/.local/bin/$1"
	elif command -v "$1" >/dev/null 2>&1; then
		command -v "$1"
	fi
}

CYPHER_MENU="$(from_repo hayami-menu)"
CYPHER_SHELL="$(from_repo hayami-shell)"

# Re-bake the launcher's menu and provider caches from the (possibly new) TOMLs.
if [ -n "$CYPHER_MENU" ]; then
	if "$CYPHER_MENU" --refresh >/dev/null 2>&1; then
		echo "Launcher menu caches refreshed."
	else
		echo "Note: Launcher cache refresh failed; the menus may be stale until the next run."
	fi
else
	echo "Note: hayami-menu not found, skipping the launcher cache refresh."
fi

# Hyprland first, then the shell that draws on it.
#
# The compositor has to re-read hypr/*.lua for the same reason the shell has to
# re-read its QML, and it is the case that stow's layout can actually hide: stow
# folds some directories whole (~/.config/hypr/apps and ~/.config/hypr/bindings are
# symlinks, so a file the commit added under either is live as soon as the repo is
# updated) but links the top level file by file. A new hypr/.config/hypr/*.lua, or
# a new directory beside one, is therefore NOT in $HOME until stow has run.
# Reloading here makes new hypr config live on the strength of the install rather
# than on whether stow happened to fold the new file's parent directory.
#
# Before the shell, deliberately: the bar is a layer surface, so it should come up
# into a session that already has its final reserved strip (hayami_bar_gaps in
# looknfeel.lua) and its layer rules (apps/bar.lua) in place, instead of drawing
# under the old ones for a moment and being re-geometried.
if command -v hyprctl >/dev/null 2>&1 && hyprctl version >/dev/null 2>&1; then
	if hyprctl reload >/dev/null 2>&1; then
		echo "Hyprland config reloaded after stowing."
	else
		echo "Note: could not reload the Hyprland config; run 'hyprctl reload' to apply it."
	fi
fi

# The shell is the whole desktop chrome (bar, launcher, notifications, OSD), so it
# should be up. Starting it here is only meaningful from inside a graphical
# session; elsewhere the next login starts it through hypr/autostart.lua.
if [ -n "$CYPHER_SHELL" ]; then
	if "$CYPHER_SHELL" status >/dev/null 2>&1; then
		# `reload` is a restart on purpose -- see the header, and hayami-shell's own
		# -- and this is the restow case it exists for. It is safe to do with the
		# session in use: the bar's own state (edge, hidden modules, calendar
		# settings) is kept in ~/.local/state/hayami-shell/bar.json and read back on
		# the way up, so the bar comes back where it was rather than on the default
		# edge.
		if "$CYPHER_SHELL" reload >/dev/null 2>&1; then
			echo "hayami-shell reloaded onto the new config."
		else
			echo "Note: hayami-shell is running but could not be reloaded."
			echo "      Run 'hayami-shell reload' to pick up the new config."
		fi
	elif "$CYPHER_SHELL" start >/dev/null 2>&1; then
		echo "hayami-shell started."
	else
		echo "Note: hayami-shell is not running (no graphical session?) — it starts at login."
	fi
else
	echo "Note: hayami-shell not found, skipping."
fi
