#!/bin/bash

# restart_launcher.sh - Make the launcher's cached menu tree match the menu TOMLs
# on disk, and make sure the shell that draws it is running.
#
# The menus are authored in quickshell/.config/quickshell/cypher-shell/menus/*.toml,
# but the launcher reads a snapshot of them generated by menus-json.py (for menus)
# and providers-json.py (for the Scripts provider). A menu edited on disk does not
# appear until that snapshot is re-baked, which is what `cypher-menu --refresh`
# does.
#
# Nothing has to be restarted for the new content to show: the shell watches both
# cache files, so writing them is enough. The shell is only started if it is not
# already up, which is the case on a first install and at the end of a migration.

set -e

DOTFILES_DIR="$(dirname "$(dirname "$(realpath "$0")")")"
[ -d "$DOTFILES_DIR/hypr" ] || DOTFILES_DIR="$HOME/.dotfiles"

# The commands are looked up in the repo first, because this runs before (or
# instead of) a restow in some paths, and ~/.local/bin may not have them yet.
from_repo() {
	if [ -x "$DOTFILES_DIR/bin/.local/bin/$1" ]; then
		printf '%s\n' "$DOTFILES_DIR/bin/.local/bin/$1"
	elif command -v "$1" >/dev/null 2>&1; then
		command -v "$1"
	fi
}

CYPHER_MENU="$(from_repo cypher-menu)"
CYPHER_SHELL="$(from_repo cypher-shell)"

# Re-bake the launcher's menu and provider caches from the (possibly new) TOMLs.
if [ -n "$CYPHER_MENU" ]; then
	if "$CYPHER_MENU" --refresh >/dev/null 2>&1; then
		echo "Launcher menu caches refreshed."
	else
		echo "Note: Launcher cache refresh failed; the menus may be stale until the next run."
	fi
else
	echo "Note: cypher-menu not found, skipping the launcher cache refresh."
fi

# The shell is the whole desktop chrome (bar, launcher, notifications, OSD), so it
# should be up. Starting it here is only meaningful from inside a graphical
# session; elsewhere the next login starts it through hypr/autostart.lua.
if [ -n "$CYPHER_SHELL" ]; then
	if "$CYPHER_SHELL" status >/dev/null 2>&1; then
		echo "cypher-shell is running."
	elif "$CYPHER_SHELL" start >/dev/null 2>&1; then
		echo "cypher-shell started."
	else
		echo "Note: cypher-shell is not running (no graphical session?) — it starts at login."
	fi
else
	echo "Note: cypher-shell not found, skipping."
fi
